(() => {
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(c)||0)/100);
  const fmtDate=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString([], {month:'short',day:'numeric',year:'numeric'});};
  let state={rows:[],referrals:[],users:[],q:'',user:'',status:''};
  const userLabel=id=>{const u=state.users.find(x=>String(x.user_id)===String(id));return u?.display_name||u?.email||'Unknown user';};
  function filtered(){const q=state.q.toLowerCase();return state.rows.filter(r=>(!state.user||String(r.user_id)===state.user)&&(!state.status||String(r.status)===state.status)&&(!q||[userLabel(r.user_id),r.client_name,r.status].join(' ').toLowerCase().includes(q)));}
  function renderSummary(){const rows=filtered();const pending=rows.filter(r=>r.status==='pending').reduce((s,r)=>s+(Number(r.commission_amount_cents)||0),0);const waiting=rows.filter(r=>r.status==='waiting_client_payment').reduce((s,r)=>s+(Number(r.commission_amount_cents)||0),0);const paid=rows.filter(r=>r.status==='complete').reduce((s,r)=>s+(Number(r.commission_amount_cents)||0),0);document.getElementById('adminPayoutSummary').innerHTML='<div><strong>'+money(waiting)+'</strong><span>Waiting</span></div><div><strong>'+money(pending)+'</strong><span>Pending</span></div><div><strong>'+money(paid)+'</strong><span>Paid</span></div><div><strong>'+rows.length+'</strong><span>Payout records</span></div>';document.getElementById('adminPayoutCount').textContent=String(rows.length);}
  function render(){
    renderSummary();const rows=filtered(),list=document.getElementById('adminPayoutList');
    list.innerHTML=rows.length?rows.map(r=>'<button class="admin-finance-row" data-payout-id="'+esc(r.id)+'"><span class="admin-finance-icon"><i data-lucide="circle-dollar-sign"></i></span><span class="admin-finance-main"><strong>'+esc(userLabel(r.user_id))+'</strong><small>'+esc(r.client_name||'Client')+' · '+esc(fmtDate(r.updated_at||r.created_at))+'</small><span><b>'+money(r.commission_amount_cents)+'</b></span></span><span class="admin-finance-status '+esc(r.status||'')+'">'+esc((r.status||'unknown').replace(/_/g,' '))+'</span><i data-lucide="chevron-right"></i></button>').join(''):'<div class="cc-empty">No payouts match.</div>';
    list.querySelectorAll('[data-payout-id]').forEach(b=>b.onclick=()=>openPayout(b.dataset.payoutId));
    const ref=document.getElementById('adminReferralPayoutList');document.getElementById('adminReferralPayoutCount').textContent=String(state.referrals.length);
    ref.innerHTML=state.referrals.length?state.referrals.map(r=>'<button class="admin-finance-row" data-ref-id="'+esc(r.id)+'"><span class="admin-finance-icon"><i data-lucide="gift"></i></span><span class="admin-finance-main"><strong>'+esc(userLabel(r.referrer_user_id))+'</strong><small>Referral bonus · '+esc(fmtDate(r.created_at))+'</small><span><b>'+money(r.amount_cents)+'</b></span></span><span class="admin-finance-status '+esc(r.status||'')+'">'+esc(r.status||'unknown')+'</span><i data-lucide="chevron-right"></i></button>').join(''):'<div class="cc-empty">No referral payouts.</div>';
    ref.querySelectorAll('[data-ref-id]').forEach(b=>b.onclick=()=>openReferral(b.dataset.refId));window.lucide?.createIcons();
  }
  function openPayout(id){const r=state.rows.find(x=>String(x.id)===String(id));if(!r)return;const ov=document.getElementById('adminFinanceDrawerOverlay'),dr=document.getElementById('adminFinanceDrawer');dr.innerHTML='<div class="admin-user-drawer-head"><div><span class="admin-kicker">PAYOUT</span><h2>'+esc(userLabel(r.user_id))+'</h2><p>'+esc(r.client_name||'Client')+'</p></div><button id="closeFinanceDrawer"><i data-lucide="x"></i></button></div><div class="admin-user-detail-grid"><div><span>Commission</span><strong>'+money(r.commission_amount_cents)+'</strong></div><div><span>Sale</span><strong>'+money(r.sale_amount_cents)+'</strong></div><div><span>Created</span><strong>'+esc(fmtDate(r.created_at))+'</strong></div><div><span>Completed</span><strong>'+esc(fmtDate(r.completed_at))+'</strong></div></div><div class="admin-lead-form-grid"><label class="full">Status<select id="payoutStatus"><option value="waiting_client_payment">Waiting on client payment</option><option value="pending">Pending</option><option value="complete">Paid / Complete</option></select></label><label class="full">Commission amount ($)<input id="payoutAmount" type="number" step="0.01" value="'+((Number(r.commission_amount_cents)||0)/100).toFixed(2)+'"></label></div><div class="admin-lead-actions"><button class="primary" id="savePayout"><i data-lucide="save"></i>Save Payout</button><button class="danger" id="deletePayout"><i data-lucide="trash-2"></i>Delete Payout</button></div><p id="payoutMessage" class="admin-user-action-message"></p>';ov.hidden=false;dr.querySelector('#closeFinanceDrawer').onclick=()=>ov.hidden=true;dr.querySelector('#payoutStatus').value=r.status||'waiting_client_payment';dr.querySelector('#savePayout').onclick=async()=>{const msg=dr.querySelector('#payoutMessage'),status=dr.querySelector('#payoutStatus').value,payload={status,commission_amount_cents:Math.round((Number(dr.querySelector('#payoutAmount').value)||0)*100),updated_at:new Date().toISOString(),completed_at:status==='complete'?(r.completed_at||new Date().toISOString()):null};const {data,error}=await window.steadyHandsCRMClient.from('callcenter_commissions').update(payload).eq('id',r.id).select('*').single();if(error){msg.textContent=error.message;return;}Object.assign(r,data);msg.textContent='Payout saved.';render();};dr.querySelector('#deletePayout').onclick=async()=>{if(!confirm('Permanently delete this payout/deal record?'))return;const {error}=await window.steadyHandsCRMClient.from('callcenter_commissions').delete().eq('id',r.id);const msg=dr.querySelector('#payoutMessage');if(error){msg.textContent=error.message;return;}state.rows=state.rows.filter(x=>String(x.id)!==String(r.id));ov.hidden=true;render();};window.lucide?.createIcons();}
  function openReferral(id){const r=state.referrals.find(x=>String(x.id)===String(id));if(!r)return;const ov=document.getElementById('adminFinanceDrawerOverlay'),dr=document.getElementById('adminFinanceDrawer');dr.innerHTML='<div class="admin-user-drawer-head"><div><span class="admin-kicker">REFERRAL PAYOUT</span><h2>'+esc(userLabel(r.referrer_user_id))+'</h2><p>'+money(r.amount_cents)+'</p></div><button id="closeFinanceDrawer"><i data-lucide="x"></i></button></div><div class="admin-lead-form-grid"><label>Status<select id="refStatus"><option value="pending">Pending</option><option value="complete">Complete</option></select></label><label>Amount ($)<input id="refAmount" type="number" step="0.01" value="'+((Number(r.amount_cents)||0)/100).toFixed(2)+'"></label></div><div class="admin-lead-actions"><button class="primary" id="saveRef"><i data-lucide="save"></i>Save Referral Payout</button><button class="danger" id="deleteRef"><i data-lucide="trash-2"></i>Delete Referral Payout</button></div><p id="refMessage" class="admin-user-action-message"></p>';ov.hidden=false;dr.querySelector('#closeFinanceDrawer').onclick=()=>ov.hidden=true;dr.querySelector('#refStatus').value=r.status||'pending';dr.querySelector('#saveRef').onclick=async()=>{const {data,error}=await window.steadyHandsCRMClient.from('callcenter_referral_bonuses').update({status:dr.querySelector('#refStatus').value,amount_cents:Math.round((Number(dr.querySelector('#refAmount').value)||0)*100),updated_at:new Date().toISOString()}).eq('id',r.id).select('*').single();const msg=dr.querySelector('#refMessage');if(error){msg.textContent=error.message;return;}Object.assign(r,data);msg.textContent='Referral payout saved.';render();};dr.querySelector('#deleteRef').onclick=async()=>{if(!confirm('Permanently delete this referral payout?'))return;const {error}=await window.steadyHandsCRMClient.from('callcenter_referral_bonuses').delete().eq('id',r.id);const msg=dr.querySelector('#refMessage');if(error){msg.textContent=error.message;return;}state.referrals=state.referrals.filter(x=>String(x.id)!==String(r.id));ov.hidden=true;render();};window.lucide?.createIcons();}
  async function load(){try{const c=window.steadyHandsCRMClient;const [a,b,d]=await Promise.all([c.from('callcenter_commissions').select('*').order('created_at',{ascending:false}).limit(10000),c.from('callcenter_profiles').select('user_id,display_name,email').order('display_name'),c.from('callcenter_referral_bonuses').select('*').order('created_at',{ascending:false}).limit(10000)]);if(a.error)throw a.error;if(b.error)throw b.error;if(d.error)throw d.error;state.rows=a.data||[];state.users=b.data||[];state.referrals=d.data||[];document.getElementById('adminPayoutUserFilter').innerHTML='<option value="">All users</option>'+state.users.map(u=>'<option value="'+esc(u.user_id)+'">'+esc(u.display_name||u.email||'User')+'</option>').join('');render();}catch(error){document.getElementById('adminPayoutList').innerHTML='<section class="admin-dashboard-error"><strong>Unable to load payouts.</strong><p>'+esc(error?.message||'Please refresh.')+'</p></section>';}}
  document.getElementById('adminPayoutSearch')?.addEventListener('input',e=>{state.q=e.target.value||'';render();});document.getElementById('adminPayoutUserFilter')?.addEventListener('change',e=>{state.user=e.target.value||'';render();});document.getElementById('adminPayoutStatusFilter')?.addEventListener('change',e=>{state.status=e.target.value||'';render();});
  if(window.steadyHandsAdminSession)load();else window.addEventListener('steadyhands:admin-ready',load,{once:true});
})();